### ISSUE TITLE
Handle emojis

### ISSUE THREAD

**Issue by samadii** [GauthamramRavichandran/clearurls#6]
If a URL has 'https://' at the first, it will be replaced with 'http://ttps//' in the cleaned one !!

And If a URL has 'http://' at the first, it will be replaced with 'http://ttp//' in the cleaned one !!

Please fix it.

**Comment by GauthamramRavichandran** [comment]
Could you provide an example or attach a screenshot of the said bug? Bot is working fine with both URL types you mentioned.

**Comment by samadii** [comment]
Oh :) i found the reason.
It will happen only when there is an emoji in the text before URL, and not a problem at all
![Screenshot_2021-06-13-14-41-30](https://user-images.githubusercontent.com/77415087/121803474-131fbc00-cc57-11eb-9b85-f25e97c3b0a6.png)

**Comment by GauthamramRavichandran** [comment]
Thank you for your screenshot, will try to handle emojis

**Comment by GauthamramRavichandran** [comment]
Fixed with recent commit.
