### ISSUE TITLE
clear urls having ampproject in them

### ISSUE THREAD

**Issue by SpEcHiDe** [GauthamramRavichandran/clearurls#7]
![20220525_103809](https://user-images.githubusercontent.com/6317196/170184283-043d7a46-fdb2-4a7c-9ff7-1edc2559180e.jpg)

**Comment by GauthamramRavichandran** [comment]
Hi Spechide, As you might already know that clearurls bot is just a wrapper around the [unalix library](https://github.com/AmanoTeam/Unalix).
 Cleaning amp url would be an upstream feature, pls create an issue in their repo. 
I'm closing this issue, since it's not applicable here.
