### ISSUE TITLE
New Twitter tracking parameters aren't cleaned

### ISSUE THREAD

**Issue by agneevX** [GauthamramRavichandran/clearurls#8]
Hello,

It seems that Twitter URLs that contains the `t` parameter aren't cleaned. Here's an example:

```
https://twitter.com/lhfang/status/1587095890983936000?t=R47JuE25EheT-zh_8pk8jg
```

Great bot, btw!

**Comment by GauthamramRavichandran** [comment]
Hi Agneev, 
As you might already know that clearurls bot is just a wrapper around the [unalix](https://github.com/AmanoTeam/Unalix) library.
This is an upstream feature, pls create an issue in their repo.
I'm closing this issue, since it's not applicable here.

Thank you,

**Comment by agneevX** [comment]
Hey, thanks for getting back. I forgot actually but I was going to close this issue since I managed to pull unalix and compile from source.
